name: Validate Terraform Formatting and Configuration

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-syntax-check:
    runs-on: ubuntu-latest
    name: Terraform Syntax Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Check Terraform Syntax
        run: |
          terraform init -backend=false
          terraform plan -out=tfplan
        shell: bash

  terraform-fmt:
    runs-on: ubuntu-latest
    name: Terraform Formatting Check
    needs: terraform-syntax-check  # ✅ Ensure syntax is correct before running fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Run Terraform fmt check on all files
        run: terraform fmt -check -recursive

  terraform-validate:
    runs-on: ubuntu-latest
    name: Terraform Validation Check
    needs: terraform-fmt  # ✅ Ensure fmt is correct before running validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform Configuration
        run: terraform validate
