name: Validate Terraform Code

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    name: Terraform Formatting Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Run Terraform fmt check on all files
        run: |
          set -e
          terraform fmt -check -recursive