name: Validate Terraform Formatting and Configuration

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    name: Terraform Formatting Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Run Terraform fmt check on all files
        run: terraform fmt -check -recursive

  terraform-validate:
    runs-on: ubuntu-latest
    name: Terraform Validation Check
    needs: terraform-fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate
